package com.evpa.guice.example;

import com.evpa.guice.example.config.BillingModule;
import com.evpa.guice.example.service.BillingService;
import com.google.inject.Guice;
import com.google.inject.Injector;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Injector injector = Guice.createInjector(new BillingModule());
        BillingService billingService = injector.getInstance(BillingService.class);
        System.out.println(billingService);
    }
}
