package com.evpa.guice.example;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.evpa.guice.example.config.BillingModule;
import com.evpa.guice.example.service.BillingService;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void testAppInjector() {
        Injector injector = Guice.createInjector(new BillingModule());
        BillingService billingService = injector.getInstance(BillingService.class);
        assertNotNull(billingService);
    }
}
